name: 'Create release'
on:
  push:
  workflow_dispatch:
    inputs:
      release:
        description: Actually create a release?
        type: boolean
        required: false
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Conventional changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.github_token }}
          skip-version-file: true
          git-push: false

      - name: Create release
        uses: actions/create-release@v1
        if: >
          inputs.release &&
          github.ref == 'refs/heads/master' &&
          steps.changelog.outputs.skipped != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
